name: Deploy Containerized App to AWS

on:
	push:
		branches:
			- main
	 workflow_dispatch:

permissions:
	id-token: write
	contents: read

env:
	AWS_REGION: ${{ vars.AWS_REGION }}
	ECR_REPOSITORY: aws-containerized-web-app
	ECS_CLUSTER: aws-containerized-web-app-cluster
	ECS_SERVICE: aws-containerized-web-app-service

jobs:
	deploy:
		name: Build and Deploy
		runs-on: ubuntu-latest

		steps:
			- name: Checkout source code
				uses: actions/checkout@v4

			- name: Configure AWS credentials using OIDC
				uses: aws-actions/configure-aws-credentials@v6.2.3
				with:
					role-to-assume: ${{ vars.AWS_ROLE_ARN }}
					aws-region: ${{ vars.AWS_REGION }}

			- name: Login to Amazon ECR
				id: login-ecr
				uses: aws-actions/amazon-ecr-login@v2

			- name: Build, tag, and push Docker image
				env:
					ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
					IMAGE_TAG: ${{ github.sha }}
				run: |
					docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
					docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

			- name: Update ECS service
				run: |
					aws ecs update-service \
						--cluster $ECS_CLUSTER \
						--service $ECS_SERVICE \
						--force-new-deployment

			- name: Wait for ECS deployment
				run: |
					aws ecs wait services-stable \
						--cluster $ECS_CLUSTER \
						--services $ECS_SERVICE
